import { solve } from './solver';

describe('solve', () => {
  it('solves [1,2,3,4]', () => {
    expect(solve([1, 2, 3, 4])).toEqual(['(1+2+3)*4', '(1+3)*(2+4)', '1*2*3*4'].sort());
  });

  it('solves [5,5,5,1]', () => {
    expect(solve([5, 5, 5, 1])).toEqual(['(5-1/5)*5']);
  });

  it('solves [3,3,8,8]', () => {
    expect(solve([3, 3, 8, 8])).toEqual(['8/(3-8/3)']);
  });

  it('solves [7,8,9,10]', () => {
    expect(solve([7, 8, 9, 10])).toEqual(['8*9/(10-7)']);
  });

  it('returns sorted, deduplicated strings', () => {
    const result = solve([1, 2, 3, 4]);
    expect([...result].sort()).toEqual(result);
    expect(new Set(result).size).toEqual(result.length);
  });
});

// Oracle fixtures generated by running game24_server.solver.solve() in Python
// over 20 seeded random inputs (seed=42, range 1..13). Each TS run must produce
// the same set of solution strings — this catches dedup divergences the
// hand-picked fixtures above miss.
const ORACLE_FIXTURES: { input: number[]; solutions: string[] }[] = [
  { input: [1, 2, 11, 12], solutions: ['2-1+11+12', '2/(1-11/12)'] },
  { input: [3, 4, 4, 5], solutions: ['(4-3+5)*4', '3+4*4+5'] },
  {
    input: [2, 11, 12, 12],
    solutions: ['2*(11+12/12)', '2*(12-11)*12', '2*12*(12-11)'],
  },
  { input: [2, 7, 9, 10], solutions: ['(2+10)*(9-7)', '2*(9-7+10)', '7-2+9+10'] },
  { input: [1, 1, 2, 4], solutions: [] },
  { input: [1, 4, 9, 10], solutions: ['1+4+9+10'] },
  {
    input: [4, 9, 11, 12],
    solutions: ['(4+9-11)*12', '11/4*12-9', '4/(11-9)*12'],
  },
  { input: [4, 7, 9, 12], solutions: ['(4+7-9)*12', '4/(9-7)*12', '7-4+9+12'] },
  { input: [5, 8, 10, 13], solutions: [] },
  { input: [1, 3, 13, 13], solutions: ['1-3+13+13'] },
  {
    input: [5, 6, 7, 12],
    solutions: ['(5+7)/6*12', '12-(5-7)*6', '6*(7-5)+12'],
  },
  { input: [3, 4, 6, 13], solutions: ['(3+13)/4*6', '6/(13/4-3)'] },
  { input: [2, 2, 2, 7], solutions: ['(2*7-2)*2'] },
  {
    input: [5, 6, 6, 10],
    solutions: ['(6+6)/5*10', '(6-10/5)*6', '6*(10-5)-6'],
  },
  { input: [1, 8, 12, 13], solutions: [] },
  { input: [2, 2, 7, 9], solutions: [] },
  { input: [5, 9, 10, 11], solutions: ['5*9-10-11'] },
  {
    input: [4, 6, 10, 12],
    solutions: ['10/4*12-6', '4+10/6*12', '6-4+10+12'],
  },
  {
    input: [1, 2, 4, 11],
    solutions: ['(1+11)*(4-2)', '(1+11)/2*4', '2*(11-1)+4', '4-(1-11)*2'],
  },
  {
    input: [2, 4, 5, 13],
    solutions: ['2*(4-5+13)', '2+4+5+13', '4*(13-2-5)'],
  },
];

describe('solve (oracle parity)', () => {
  for (const { input, solutions } of ORACLE_FIXTURES) {
    it(`matches Python on [${input.join(',')}]`, () => {
      expect(solve(input)).toEqual(solutions.slice().sort());
    });
  }
});
